package com.visa.apply.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DBastaRowAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDBastaRowAllPropertiesEquals(DBastaRow expected, DBastaRow actual) {
        assertDBastaRowAutoGeneratedPropertiesEquals(expected, actual);
        assertDBastaRowAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDBastaRowAllUpdatablePropertiesEquals(DBastaRow expected, DBastaRow actual) {
        assertDBastaRowUpdatableFieldsEquals(expected, actual);
        assertDBastaRowUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDBastaRowAutoGeneratedPropertiesEquals(DBastaRow expected, DBastaRow actual) {
        assertThat(actual)
            .as("Verify DBastaRow auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDBastaRowUpdatableFieldsEquals(DBastaRow expected, DBastaRow actual) {
        assertThat(actual)
            .as("Verify DBastaRow relevant properties")
            .satisfies(a -> assertThat(a.getDcFamil()).as("check dcFamil").isEqualTo(expected.getDcFamil()))
            .satisfies(a -> assertThat(a.getDcImena()).as("check dcImena").isEqualTo(expected.getDcImena()))
            .satisfies(a -> assertThat(a.getDcPol()).as("check dcPol").isEqualTo(expected.getDcPol()))
            .satisfies(a -> assertThat(a.getDcGrad()).as("check dcGrad").isEqualTo(expected.getDcGrad()))
            .satisfies(a -> assertThat(a.getDcUlica()).as("check dcUlica").isEqualTo(expected.getDcUlica()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDBastaRowUpdatableRelationshipsEquals(DBastaRow expected, DBastaRow actual) {
        // empty method
    }
}
