package com.visa.apply.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DDomakinRowAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDDomakinRowAllPropertiesEquals(DDomakinRow expected, DDomakinRow actual) {
        assertDDomakinRowAutoGeneratedPropertiesEquals(expected, actual);
        assertDDomakinRowAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDDomakinRowAllUpdatablePropertiesEquals(DDomakinRow expected, DDomakinRow actual) {
        assertDDomakinRowUpdatableFieldsEquals(expected, actual);
        assertDDomakinRowUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDDomakinRowAutoGeneratedPropertiesEquals(DDomakinRow expected, DDomakinRow actual) {
        assertThat(actual)
            .as("Verify DDomakinRow auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDDomakinRowUpdatableFieldsEquals(DDomakinRow expected, DDomakinRow actual) {
        assertThat(actual)
            .as("Verify DDomakinRow relevant properties")
            .satisfies(a -> assertThat(a.getDmVid()).as("check dmVid").isEqualTo(expected.getDmVid()))
            .satisfies(a -> assertThat(a.getNomPok()).as("check nomPok").isEqualTo(expected.getNomPok()))
            .satisfies(a -> assertThat(a.getDomGraj()).as("check domGraj").isEqualTo(expected.getDomGraj()))
            .satisfies(a -> assertThat(a.getDomFamil()).as("check domFamil").isEqualTo(expected.getDomFamil()))
            .satisfies(a -> assertThat(a.getDomIme()).as("check domIme").isEqualTo(expected.getDomIme()))
            .satisfies(a -> assertThat(a.getDomDarj()).as("check domDarj").isEqualTo(expected.getDomDarj()))
            .satisfies(a -> assertThat(a.getDomNm()).as("check domNm").isEqualTo(expected.getDomNm()))
            .satisfies(a -> assertThat(a.getDomAdres()).as("check domAdres").isEqualTo(expected.getDomAdres()))
            .satisfies(a -> assertThat(a.getVedDarj()).as("check vedDarj").isEqualTo(expected.getVedDarj()))
            .satisfies(a -> assertThat(a.getVedNm()).as("check vedNm").isEqualTo(expected.getVedNm()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDDomakinRowUpdatableRelationshipsEquals(DDomakinRow expected, DDomakinRow actual) {
        // empty method
    }
}
