package com.visa.apply.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DEurodaRowAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDEurodaRowAllPropertiesEquals(DEurodaRow expected, DEurodaRow actual) {
        assertDEurodaRowAutoGeneratedPropertiesEquals(expected, actual);
        assertDEurodaRowAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDEurodaRowAllUpdatablePropertiesEquals(DEurodaRow expected, DEurodaRow actual) {
        assertDEurodaRowUpdatableFieldsEquals(expected, actual);
        assertDEurodaRowUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDEurodaRowAutoGeneratedPropertiesEquals(DEurodaRow expected, DEurodaRow actual) {
        assertThat(actual)
            .as("Verify DEurodaRow auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDEurodaRowUpdatableFieldsEquals(DEurodaRow expected, DEurodaRow actual) {
        assertThat(actual)
            .as("Verify DEurodaRow relevant properties")
            .satisfies(a -> assertThat(a.getEuFamil()).as("check euFamil").isEqualTo(expected.getEuFamil()))
            .satisfies(a -> assertThat(a.getEuImena()).as("check euImena").isEqualTo(expected.getEuImena()))
            .satisfies(a -> assertThat(a.getEuNacBel()).as("check euNacBel").isEqualTo(expected.getEuNacBel()))
            .satisfies(a -> assertThat(a.getEuRodstvo()).as("check euRodstvo").isEqualTo(expected.getEuRodstvo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDEurodaRowUpdatableRelationshipsEquals(DEurodaRow expected, DEurodaRow actual) {
        // empty method
    }
}
