package com.visa.apply.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DFingersRowAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDFingersRowAllPropertiesEquals(DFingersRow expected, DFingersRow actual) {
        assertDFingersRowAutoGeneratedPropertiesEquals(expected, actual);
        assertDFingersRowAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDFingersRowAllUpdatablePropertiesEquals(DFingersRow expected, DFingersRow actual) {
        assertDFingersRowUpdatableFieldsEquals(expected, actual);
        assertDFingersRowUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDFingersRowAutoGeneratedPropertiesEquals(DFingersRow expected, DFingersRow actual) {
        assertThat(actual)
            .as("Verify DFingersRow auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDFingersRowUpdatableFieldsEquals(DFingersRow expected, DFingersRow actual) {
        assertThat(actual)
            .as("Verify DFingersRow relevant properties")
            .satisfies(a -> assertThat(a.getFnDatreg()).as("check fnDatreg").isEqualTo(expected.getFnDatreg()))
            .satisfies(a -> assertThat(a.getFnDatvav()).as("check fnDatvav").isEqualTo(expected.getFnDatvav()))
            .satisfies(a -> assertThat(a.getFnUsera()).as("check fnUsera").isEqualTo(expected.getFnUsera()))
            .satisfies(a -> assertThat(a.getFnSid()).as("check fnSid").isEqualTo(expected.getFnSid()))
            .satisfies(a -> assertThat(a.getFnPnr()).as("check fnPnr").isEqualTo(expected.getFnPnr()))
            .satisfies(a -> assertThat(a.getFnVidmol()).as("check fnVidmol").isEqualTo(expected.getFnVidmol()))
            .satisfies(a -> assertThat(a.getFnDrugi()).as("check fnDrugi").isEqualTo(expected.getFnDrugi()))
            .satisfies(a -> assertThat(a.getFnDeviceid()).as("check fnDeviceid").isEqualTo(expected.getFnDeviceid()))
            .satisfies(a -> assertThat(a.getFnScanres()).as("check fnScanres").isEqualTo(expected.getFnScanres()))
            .satisfies(a -> assertThat(a.getFnWidth()).as("check fnWidth").isEqualTo(expected.getFnWidth()))
            .satisfies(a -> assertThat(a.getFnHeight()).as("check fnHeight").isEqualTo(expected.getFnHeight()))
            .satisfies(a -> assertThat(a.getFnPixeldepth()).as("check fnPixeldepth").isEqualTo(expected.getFnPixeldepth()))
            .satisfies(a -> assertThat(a.getFnCompressalgo()).as("check fnCompressalgo").isEqualTo(expected.getFnCompressalgo()))
            .satisfies(a -> assertThat(a.getFnFingerposition()).as("check fnFingerposition").isEqualTo(expected.getFnFingerposition()))
            .satisfies(a -> assertThat(a.getFnImagequality()).as("check fnImagequality").isEqualTo(expected.getFnImagequality()))
            .satisfies(a -> assertThat(a.getFnImage()).as("check fnImage").isEqualTo(expected.getFnImage()))
            .satisfies(a -> assertThat(a.getFnImglen()).as("check fnImglen").isEqualTo(expected.getFnImglen()))
            .satisfies(a -> assertThat(a.getFnNottakenreason()).as("check fnNottakenreason").isEqualTo(expected.getFnNottakenreason()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDFingersRowUpdatableRelationshipsEquals(DFingersRow expected, DFingersRow actual) {
        // empty method
    }
}
