package com.visa.apply.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DImagesRowAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDImagesRowAllPropertiesEquals(DImagesRow expected, DImagesRow actual) {
        assertDImagesRowAutoGeneratedPropertiesEquals(expected, actual);
        assertDImagesRowAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDImagesRowAllUpdatablePropertiesEquals(DImagesRow expected, DImagesRow actual) {
        assertDImagesRowUpdatableFieldsEquals(expected, actual);
        assertDImagesRowUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDImagesRowAutoGeneratedPropertiesEquals(DImagesRow expected, DImagesRow actual) {
        assertThat(actual)
            .as("Verify DImagesRow auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDImagesRowUpdatableFieldsEquals(DImagesRow expected, DImagesRow actual) {
        assertThat(actual)
            .as("Verify DImagesRow relevant properties")
            .satisfies(a -> assertThat(a.getImDevicetype()).as("check imDevicetype").isEqualTo(expected.getImDevicetype()))
            .satisfies(a -> assertThat(a.getImWidth()).as("check imWidth").isEqualTo(expected.getImWidth()))
            .satisfies(a -> assertThat(a.getImHeight()).as("check imHeight").isEqualTo(expected.getImHeight()))
            .satisfies(a -> assertThat(a.getImImglen()).as("check imImglen").isEqualTo(expected.getImImglen()))
            .satisfies(a -> assertThat(a.getImImage()).as("check imImage").isEqualTo(expected.getImImage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDImagesRowUpdatableRelationshipsEquals(DImagesRow expected, DImagesRow actual) {
        // empty method
    }
}
