package com.visa.apply.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DLcdopRowAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDLcdopRowAllPropertiesEquals(DLcdopRow expected, DLcdopRow actual) {
        assertDLcdopRowAutoGeneratedPropertiesEquals(expected, actual);
        assertDLcdopRowAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDLcdopRowAllUpdatablePropertiesEquals(DLcdopRow expected, DLcdopRow actual) {
        assertDLcdopRowUpdatableFieldsEquals(expected, actual);
        assertDLcdopRowUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDLcdopRowAutoGeneratedPropertiesEquals(DLcdopRow expected, DLcdopRow actual) {
        assertThat(actual)
            .as("Verify DLcdopRow auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDLcdopRowUpdatableFieldsEquals(DLcdopRow expected, DLcdopRow actual) {
        assertThat(actual)
            .as("Verify DLcdopRow relevant properties")
            .satisfies(a -> assertThat(a.getLdMrjdarj()).as("check ldMrjdarj").isEqualTo(expected.getLdMrjdarj()))
            .satisfies(a -> assertThat(a.getLdMrjnm()).as("check ldMrjnm").isEqualTo(expected.getLdMrjnm()))
            .satisfies(a -> assertThat(a.getLdMrjgraj()).as("check ldMrjgraj").isEqualTo(expected.getLdMrjgraj()))
            .satisfies(a -> assertThat(a.getLdZenen()).as("check ldZenen").isEqualTo(expected.getLdZenen()))
            .satisfies(a -> assertThat(a.getLdJitDarj()).as("check ldJitDarj").isEqualTo(expected.getLdJitDarj()))
            .satisfies(a -> assertThat(a.getLdJitNm()).as("check ldJitNm").isEqualTo(expected.getLdJitNm()))
            .satisfies(a -> assertThat(a.getLdJitUl()).as("check ldJitUl").isEqualTo(expected.getLdJitUl()))
            .satisfies(a -> assertThat(a.getLdTel()).as("check ldTel").isEqualTo(expected.getLdTel()))
            .satisfies(a -> assertThat(a.getLdRabota()).as("check ldRabota").isEqualTo(expected.getLdRabota()))
            .satisfies(a -> assertThat(a.getLdProfkod()).as("check ldProfkod").isEqualTo(expected.getLdProfkod()))
            .satisfies(a -> assertThat(a.getLdProfesia()).as("check ldProfesia").isEqualTo(expected.getLdProfesia()))
            .satisfies(a -> assertThat(a.getLdSlDarj()).as("check ldSlDarj").isEqualTo(expected.getLdSlDarj()))
            .satisfies(a -> assertThat(a.getLdSlNm()).as("check ldSlNm").isEqualTo(expected.getLdSlNm()))
            .satisfies(a -> assertThat(a.getLdSlUl()).as("check ldSlUl").isEqualTo(expected.getLdSlUl()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDLcdopRowUpdatableRelationshipsEquals(DLcdopRow expected, DLcdopRow actual) {
        // empty method
    }
}
