package com.visa.apply.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DLcuzRowAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDLcuzRowAllPropertiesEquals(DLcuzRow expected, DLcuzRow actual) {
        assertDLcuzRowAutoGeneratedPropertiesEquals(expected, actual);
        assertDLcuzRowAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDLcuzRowAllUpdatablePropertiesEquals(DLcuzRow expected, DLcuzRow actual) {
        assertDLcuzRowUpdatableFieldsEquals(expected, actual);
        assertDLcuzRowUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDLcuzRowAutoGeneratedPropertiesEquals(DLcuzRow expected, DLcuzRow actual) {
        assertThat(actual)
            .as("Verify DLcuzRow auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDLcuzRowUpdatableFieldsEquals(DLcuzRow expected, DLcuzRow actual) {
        assertThat(actual)
            .as("Verify DLcuzRow relevant properties")
            .satisfies(a -> assertThat(a.getVidZp()).as("check vidZp").isEqualTo(expected.getVidZp()))
            .satisfies(a -> assertThat(a.getNacBel()).as("check nacBel").isEqualTo(expected.getNacBel()))
            .satisfies(a -> assertThat(a.getNacPasp()).as("check nacPasp").isEqualTo(expected.getNacPasp()))
            .satisfies(a -> assertThat(a.getPaspVal()).as("check paspVal").isEqualTo(expected.getPaspVal()))
            .satisfies(a -> assertThat(a.getGraj()).as("check graj").isEqualTo(expected.getGraj()))
            .satisfies(a -> assertThat(a.getFamil()).as("check famil").isEqualTo(expected.getFamil()))
            .satisfies(a -> assertThat(a.getImena()).as("check imena").isEqualTo(expected.getImena()))
            .satisfies(a -> assertThat(a.getDatRaj()).as("check datRaj").isEqualTo(expected.getDatRaj()))
            .satisfies(a -> assertThat(a.getPol()).as("check pol").isEqualTo(expected.getPol()))
            .satisfies(a -> assertThat(a.getDatIzd()).as("check datIzd").isEqualTo(expected.getDatIzd()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDLcuzRowUpdatableRelationshipsEquals(DLcuzRow expected, DLcuzRow actual) {
        // empty method
    }
}
