package com.visa.apply.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DLoadosfEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDLoadosfEntityAllPropertiesEquals(DLoadosfEntity expected, DLoadosfEntity actual) {
        assertDLoadosfEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertDLoadosfEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDLoadosfEntityAllUpdatablePropertiesEquals(DLoadosfEntity expected, DLoadosfEntity actual) {
        assertDLoadosfEntityUpdatableFieldsEquals(expected, actual);
        assertDLoadosfEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDLoadosfEntityAutoGeneratedPropertiesEquals(DLoadosfEntity expected, DLoadosfEntity actual) {
        assertThat(actual)
            .as("Verify DLoadosfEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDLoadosfEntityUpdatableFieldsEquals(DLoadosfEntity expected, DLoadosfEntity actual) {
        assertThat(actual)
            .as("Verify DLoadosfEntity relevant properties")
            .satisfies(a -> assertThat(a.getVersion()).as("check version").isEqualTo(expected.getVersion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDLoadosfEntityUpdatableRelationshipsEquals(DLoadosfEntity expected, DLoadosfEntity actual) {
        assertThat(actual)
            .as("Verify DLoadosfEntity relationships")
            .satisfies(a -> assertThat(a.getMsgheader()).as("check msgheader").isEqualTo(expected.getMsgheader()))
            .satisfies(a -> assertThat(a.getLcuz()).as("check lcuz").isEqualTo(expected.getLcuz()))
            .satisfies(a -> assertThat(a.getLcdop()).as("check lcdop").isEqualTo(expected.getLcdop()))
            .satisfies(a -> assertThat(a.getBastaEntity()).as("check bastaEntity").isEqualTo(expected.getBastaEntity()))
            .satisfies(a -> assertThat(a.getMaika()).as("check maika").isEqualTo(expected.getMaika()))
            .satisfies(a -> assertThat(a.getSapruga()).as("check sapruga").isEqualTo(expected.getSapruga()))
            .satisfies(a -> assertThat(a.getMolba()).as("check molba").isEqualTo(expected.getMolba()))
            .satisfies(a -> assertThat(a.getDomakin()).as("check domakin").isEqualTo(expected.getDomakin()))
            .satisfies(a -> assertThat(a.getEuroda()).as("check euroda").isEqualTo(expected.getEuroda()))
            .satisfies(a -> assertThat(a.getVoit()).as("check voit").isEqualTo(expected.getVoit()))
            .satisfies(a -> assertThat(a.getImages()).as("check images").isEqualTo(expected.getImages()))
            .satisfies(a -> assertThat(a.getFingers()).as("check fingers").isEqualTo(expected.getFingers()));
    }
}
