package com.visa.apply.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DMaikaRowAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDMaikaRowAllPropertiesEquals(DMaikaRow expected, DMaikaRow actual) {
        assertDMaikaRowAutoGeneratedPropertiesEquals(expected, actual);
        assertDMaikaRowAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDMaikaRowAllUpdatablePropertiesEquals(DMaikaRow expected, DMaikaRow actual) {
        assertDMaikaRowUpdatableFieldsEquals(expected, actual);
        assertDMaikaRowUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDMaikaRowAutoGeneratedPropertiesEquals(DMaikaRow expected, DMaikaRow actual) {
        assertThat(actual)
            .as("Verify DMaikaRow auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDMaikaRowUpdatableFieldsEquals(DMaikaRow expected, DMaikaRow actual) {
        assertThat(actual)
            .as("Verify DMaikaRow relevant properties")
            .satisfies(a -> assertThat(a.getDcFamil()).as("check dcFamil").isEqualTo(expected.getDcFamil()))
            .satisfies(a -> assertThat(a.getDcImena()).as("check dcImena").isEqualTo(expected.getDcImena()))
            .satisfies(a -> assertThat(a.getDcPol()).as("check dcPol").isEqualTo(expected.getDcPol()))
            .satisfies(a -> assertThat(a.getDcDarj()).as("check dcDarj").isEqualTo(expected.getDcDarj()))
            .satisfies(a -> assertThat(a.getDcGrad()).as("check dcGrad").isEqualTo(expected.getDcGrad()))
            .satisfies(a -> assertThat(a.getDcUlica()).as("check dcUlica").isEqualTo(expected.getDcUlica()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDMaikaRowUpdatableRelationshipsEquals(DMaikaRow expected, DMaikaRow actual) {
        // empty method
    }
}
