package com.visa.apply.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DMsgheaderRowAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDMsgheaderRowAllPropertiesEquals(DMsgheaderRow expected, DMsgheaderRow actual) {
        assertDMsgheaderRowAutoGeneratedPropertiesEquals(expected, actual);
        assertDMsgheaderRowAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDMsgheaderRowAllUpdatablePropertiesEquals(DMsgheaderRow expected, DMsgheaderRow actual) {
        assertDMsgheaderRowUpdatableFieldsEquals(expected, actual);
        assertDMsgheaderRowUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDMsgheaderRowAutoGeneratedPropertiesEquals(DMsgheaderRow expected, DMsgheaderRow actual) {
        assertThat(actual)
            .as("Verify DMsgheaderRow auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDMsgheaderRowUpdatableFieldsEquals(DMsgheaderRow expected, DMsgheaderRow actual) {
        assertThat(actual)
            .as("Verify DMsgheaderRow relevant properties")
            .satisfies(a -> assertThat(a.getMhKscreated()).as("check mhKscreated").isEqualTo(expected.getMhKscreated()))
            .satisfies(a -> assertThat(a.getMhRegnom()).as("check mhRegnom").isEqualTo(expected.getMhRegnom()))
            .satisfies(a -> assertThat(a.getMhVfsrefno()).as("check mhVfsrefno").isEqualTo(expected.getMhVfsrefno()))
            .satisfies(a -> assertThat(a.getMhUsera()).as("check mhUsera").isEqualTo(expected.getMhUsera()))
            .satisfies(a -> assertThat(a.getMhDatvav()).as("check mhDatvav").isEqualTo(expected.getMhDatvav()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDMsgheaderRowUpdatableRelationshipsEquals(DMsgheaderRow expected, DMsgheaderRow actual) {
        // empty method
    }
}
