package com.visa.apply.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DSaprugaRowAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDSaprugaRowAllPropertiesEquals(DSaprugaRow expected, DSaprugaRow actual) {
        assertDSaprugaRowAutoGeneratedPropertiesEquals(expected, actual);
        assertDSaprugaRowAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDSaprugaRowAllUpdatablePropertiesEquals(DSaprugaRow expected, DSaprugaRow actual) {
        assertDSaprugaRowUpdatableFieldsEquals(expected, actual);
        assertDSaprugaRowUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDSaprugaRowAutoGeneratedPropertiesEquals(DSaprugaRow expected, DSaprugaRow actual) {
        assertThat(actual)
            .as("Verify DSaprugaRow auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDSaprugaRowUpdatableFieldsEquals(DSaprugaRow expected, DSaprugaRow actual) {
        assertThat(actual)
            .as("Verify DSaprugaRow relevant properties")
            .satisfies(a -> assertThat(a.getSpMrjdarj()).as("check spMrjdarj").isEqualTo(expected.getSpMrjdarj()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDSaprugaRowUpdatableRelationshipsEquals(DSaprugaRow expected, DSaprugaRow actual) {
        // empty method
    }
}
