package com.visa.apply.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DVoitRowAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDVoitRowAllPropertiesEquals(DVoitRow expected, DVoitRow actual) {
        assertDVoitRowAutoGeneratedPropertiesEquals(expected, actual);
        assertDVoitRowAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDVoitRowAllUpdatablePropertiesEquals(DVoitRow expected, DVoitRow actual) {
        assertDVoitRowUpdatableFieldsEquals(expected, actual);
        assertDVoitRowUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDVoitRowAutoGeneratedPropertiesEquals(DVoitRow expected, DVoitRow actual) {
        assertThat(actual)
            .as("Verify DVoitRow auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDVoitRowUpdatableFieldsEquals(DVoitRow expected, DVoitRow actual) {
        assertThat(actual)
            .as("Verify DVoitRow relevant properties")
            .satisfies(a -> assertThat(a.getVnom()).as("check vnom").isEqualTo(expected.getVnom()))
            .satisfies(a -> assertThat(a.getVime()).as("check vime").isEqualTo(expected.getVime()))
            .satisfies(a -> assertThat(a.getBgime()).as("check bgime").isEqualTo(expected.getBgime()))
            .satisfies(a -> assertThat(a.getBgadres()).as("check bgadres").isEqualTo(expected.getBgadres()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDVoitRowUpdatableRelationshipsEquals(DVoitRow expected, DVoitRow actual) {
        // empty method
    }
}
