package com.visa.apply.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MolbaRowAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMolbaRowAllPropertiesEquals(MolbaRow expected, MolbaRow actual) {
        assertMolbaRowAutoGeneratedPropertiesEquals(expected, actual);
        assertMolbaRowAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMolbaRowAllUpdatablePropertiesEquals(MolbaRow expected, MolbaRow actual) {
        assertMolbaRowUpdatableFieldsEquals(expected, actual);
        assertMolbaRowUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMolbaRowAutoGeneratedPropertiesEquals(MolbaRow expected, MolbaRow actual) {
        assertThat(actual)
            .as("Verify MolbaRow auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMolbaRowUpdatableFieldsEquals(MolbaRow expected, MolbaRow actual) {
        assertThat(actual)
            .as("Verify MolbaRow relevant properties")
            .satisfies(a -> assertThat(a.getDatVli()).as("check datVli").isEqualTo(expected.getDatVli()))
            .satisfies(a -> assertThat(a.getDatIzl()).as("check datIzl").isEqualTo(expected.getDatIzl()))
            .satisfies(a -> assertThat(a.getVidvis()).as("check vidvis").isEqualTo(expected.getVidvis()))
            .satisfies(a -> assertThat(a.getBrvl()).as("check brvl").isEqualTo(expected.getBrvl()))
            .satisfies(a -> assertThat(a.getVidus()).as("check vidus").isEqualTo(expected.getVidus()))
            .satisfies(a -> assertThat(a.getValvis()).as("check valvis").isEqualTo(expected.getValvis()))
            .satisfies(a -> assertThat(a.getBrdni()).as("check brdni").isEqualTo(expected.getBrdni()))
            .satisfies(a -> assertThat(a.getCel()).as("check cel").isEqualTo(expected.getCel()))
            .satisfies(a -> assertThat(a.getMolDatVav()).as("check molDatVav").isEqualTo(expected.getMolDatVav()))
            .satisfies(a -> assertThat(a.getGratis()).as("check gratis").isEqualTo(expected.getGratis()))
            .satisfies(a -> assertThat(a.getImavisa()).as("check imavisa").isEqualTo(expected.getImavisa()))
            .satisfies(a -> assertThat(a.getCenamol()).as("check cenamol").isEqualTo(expected.getCenamol()))
            .satisfies(a -> assertThat(a.getCenacurr()).as("check cenacurr").isEqualTo(expected.getCenacurr()))
            .satisfies(a -> assertThat(a.getMaindest()).as("check maindest").isEqualTo(expected.getMaindest()))
            .satisfies(a -> assertThat(a.getMaindestnm()).as("check maindestnm").isEqualTo(expected.getMaindestnm()))
            .satisfies(a -> assertThat(a.getGkppDarj()).as("check gkppDarj").isEqualTo(expected.getGkppDarj()))
            .satisfies(a -> assertThat(a.getGkppText()).as("check gkppText").isEqualTo(expected.getGkppText()))
            .satisfies(a -> assertThat(a.getTextIni()).as("check textIni").isEqualTo(expected.getTextIni()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMolbaRowUpdatableRelationshipsEquals(MolbaRow expected, MolbaRow actual) {
        // empty method
    }
}
